# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jack/Desktop/gitmt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jack/Desktop/gitmt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Desktop/gitmt/CMakeFiles /home/jack/Desktop/gitmt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Desktop/gitmt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mt

# Build rule for target.
mt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mt
.PHONY : mt

# fast build rule for target.
mt/fast:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/build
.PHONY : mt/fast

src/configreader.o: src/configreader.cpp.o
.PHONY : src/configreader.o

# target to build an object file
src/configreader.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/configreader.cpp.o
.PHONY : src/configreader.cpp.o

src/configreader.i: src/configreader.cpp.i
.PHONY : src/configreader.i

# target to preprocess a source file
src/configreader.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/configreader.cpp.i
.PHONY : src/configreader.cpp.i

src/configreader.s: src/configreader.cpp.s
.PHONY : src/configreader.s

# target to generate assembly for a file
src/configreader.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/configreader.cpp.s
.PHONY : src/configreader.cpp.s

src/dcdio.o: src/dcdio.cpp.o
.PHONY : src/dcdio.o

# target to build an object file
src/dcdio.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/dcdio.cpp.o
.PHONY : src/dcdio.cpp.o

src/dcdio.i: src/dcdio.cpp.i
.PHONY : src/dcdio.i

# target to preprocess a source file
src/dcdio.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/dcdio.cpp.i
.PHONY : src/dcdio.cpp.i

src/dcdio.s: src/dcdio.cpp.s
.PHONY : src/dcdio.s

# target to generate assembly for a file
src/dcdio.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/dcdio.cpp.s
.PHONY : src/dcdio.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parameters.o: src/parameters.cpp.o
.PHONY : src/parameters.o

# target to build an object file
src/parameters.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/parameters.cpp.o
.PHONY : src/parameters.cpp.o

src/parameters.i: src/parameters.cpp.i
.PHONY : src/parameters.i

# target to preprocess a source file
src/parameters.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/parameters.cpp.i
.PHONY : src/parameters.cpp.i

src/parameters.s: src/parameters.cpp.s
.PHONY : src/parameters.s

# target to generate assembly for a file
src/parameters.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/parameters.cpp.s
.PHONY : src/parameters.cpp.s

src/pdbio.o: src/pdbio.cpp.o
.PHONY : src/pdbio.o

# target to build an object file
src/pdbio.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/pdbio.cpp.o
.PHONY : src/pdbio.cpp.o

src/pdbio.i: src/pdbio.cpp.i
.PHONY : src/pdbio.i

# target to preprocess a source file
src/pdbio.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/pdbio.cpp.i
.PHONY : src/pdbio.cpp.i

src/pdbio.s: src/pdbio.cpp.s
.PHONY : src/pdbio.s

# target to generate assembly for a file
src/pdbio.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/pdbio.cpp.s
.PHONY : src/pdbio.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/wrapper.o: src/wrapper.cpp.o
.PHONY : src/wrapper.o

# target to build an object file
src/wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/wrapper.cpp.o
.PHONY : src/wrapper.cpp.o

src/wrapper.i: src/wrapper.cpp.i
.PHONY : src/wrapper.i

# target to preprocess a source file
src/wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/wrapper.cpp.i
.PHONY : src/wrapper.cpp.i

src/wrapper.s: src/wrapper.cpp.s
.PHONY : src/wrapper.s

# target to generate assembly for a file
src/wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/wrapper.cpp.s
.PHONY : src/wrapper.cpp.s

src/xyzio.o: src/xyzio.cpp.o
.PHONY : src/xyzio.o

# target to build an object file
src/xyzio.cpp.o:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/xyzio.cpp.o
.PHONY : src/xyzio.cpp.o

src/xyzio.i: src/xyzio.cpp.i
.PHONY : src/xyzio.i

# target to preprocess a source file
src/xyzio.cpp.i:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/xyzio.cpp.i
.PHONY : src/xyzio.cpp.i

src/xyzio.s: src/xyzio.cpp.s
.PHONY : src/xyzio.s

# target to generate assembly for a file
src/xyzio.cpp.s:
	$(MAKE) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/src/xyzio.cpp.s
.PHONY : src/xyzio.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mt"
	@echo "... rebuild_cache"
	@echo "... src/configreader.o"
	@echo "... src/configreader.i"
	@echo "... src/configreader.s"
	@echo "... src/dcdio.o"
	@echo "... src/dcdio.i"
	@echo "... src/dcdio.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parameters.o"
	@echo "... src/parameters.i"
	@echo "... src/parameters.s"
	@echo "... src/pdbio.o"
	@echo "... src/pdbio.i"
	@echo "... src/pdbio.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/wrapper.o"
	@echo "... src/wrapper.i"
	@echo "... src/wrapper.s"
	@echo "... src/xyzio.o"
	@echo "... src/xyzio.i"
	@echo "... src/xyzio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

